In [1]:
import tensorflow

In [20]:
# 예제1.  

import  tensorflow  as  tf

sess = tf.Session()  # 그래프를 실행할 세션을 구성한다. 
hello = tf.constant('Hello, Tensorflow')

print ( sess.run(hello)) 
print (str(sess.run(hello), encoding="utf-8"))

b'Hello, Tensorflow'
Hello, Tensorflow


In [29]:
#예제2.

import  tensorflow  as  tf

x = tf.constant(35, name='x')
y = tf.Variable( x + 5, name='y')
model = tf.global_variables_initializer()

sess = tf.Session()
sess.run(model)

print (sess.run(y)) 

40


In [33]:
#예제3.

import  tensorflow  as  tf

a = tf.constant(10)
b = tf.constant(32)
c = tf.add(a,b)
print(c)

Tensor("Add_5:0", shape=(), dtype=int32)


In [34]:
#문제1. 위에서 만든 텐써 그래프를 실행하시오 !

sess = tf.Session()
print (sess.run(c))

42


In [36]:
#문제2. 아래의 모델(그래프) 를 실행하시오 !

import  tensorflow  as  tf

a = tf.add(1,2)
b = tf.multiply(a,3)
c = tf.add(b,5)
d = tf.multiply(c,6)
e = tf.multiply(d,5)
f = tf.div(e,6)
g = tf.add(f,d)
h = tf.multiply(g,f)

sess = tf.Session()
print (sess.run(h)) 
sess.close()

10780


In [37]:
#문제3. 위의 예제를 with 절 사용해서 구현하시오 !

import  tensorflow  as  tf

a = tf.add(1,2)
b = tf.multiply(a,3)
c = tf.add(b,5)
d = tf.multiply(c,6)
e = tf.multiply(d,5)
f = tf.div(e,6)
g = tf.add(f,d)
h = tf.multiply(g,f)

# sess = tf.Session()
# print (sess.run(h)) 
# sess.close()  <---  세션을 닫는 구문을 작성해줘야한다. 

with  tf.Session()  as  sess:
    print ( sess.run(h) )

10780


In [40]:
#문제4. 위의 코드를 이용해서 구구단 2단을 출력하시오 !

#  tf.multiply 를 활용하세요 !

#  2 x 1 = 2
#  2 x 2 = 4
#  2 x 3 = 6
#     :
#  2 x 9 = 18 

import  tensorflow  as  tf

x = tf.Variable(2)
y = tf.Variable(1)

model = tf.global_variables_initializer()

sess = tf.Session()

sess.run(model)

for i in  range(9):
    z = tf.multiply(x,y)
    print ( sess.run(x)," x ", sess.run(y), " = " , sess.run(z))
    y = y + 1

2  x  1  =  2
2  x  2  =  4
2  x  3  =  6
2  x  4  =  8
2  x  5  =  10
2  x  6  =  12
2  x  7  =  14
2  x  8  =  16
2  x  9  =  18


In [41]:
# 문제5. 구구단 2단에서 9단까지 출력하시오 ! 

import  tensorflow  as  tf

x = tf.Variable(0)
y = tf.Variable(0)
z = tf.multiply(x,y)

model = tf.global_variables_initializer()

sess = tf.Session()

sess.run(model)

for i in  range(2,10):
    for j in  range(1,10):
        print (i," x ", j," = ",sess.run(z,feed_dict={x:i,y:j}))

2  x  1  =  2
2  x  2  =  4
2  x  3  =  6
2  x  4  =  8
2  x  5  =  10
2  x  6  =  12
2  x  7  =  14
2  x  8  =  16
2  x  9  =  18
3  x  1  =  3
3  x  2  =  6
3  x  3  =  9
3  x  4  =  12
3  x  5  =  15
3  x  6  =  18
3  x  7  =  21
3  x  8  =  24
3  x  9  =  27
4  x  1  =  4
4  x  2  =  8
4  x  3  =  12
4  x  4  =  16
4  x  5  =  20
4  x  6  =  24
4  x  7  =  28
4  x  8  =  32
4  x  9  =  36
5  x  1  =  5
5  x  2  =  10
5  x  3  =  15
5  x  4  =  20
5  x  5  =  25
5  x  6  =  30
5  x  7  =  35
5  x  8  =  40
5  x  9  =  45
6  x  1  =  6
6  x  2  =  12
6  x  3  =  18
6  x  4  =  24
6  x  5  =  30
6  x  6  =  36
6  x  7  =  42
6  x  8  =  48
6  x  9  =  54
7  x  1  =  7
7  x  2  =  14
7  x  3  =  21
7  x  4  =  28
7  x  5  =  35
7  x  6  =  42
7  x  7  =  49
7  x  8  =  56
7  x  9  =  63
8  x  1  =  8
8  x  2  =  16
8  x  3  =  24
8  x  4  =  32
8  x  5  =  40
8  x  6  =  48
8  x  7  =  56
8  x  8  =  64
8  x  9  =  72
9  x  1  =  9
9  x  2  =  18
9  x  3  =  27
9  x  4  =  36
9  x  5  

In [43]:
#문제6.(점심시간 문제) 아래의 텐써 그래프를 실행하시오 ! 숫자는 알아서 feed 하세요 ~

import  tensorflow  as  tf

a = tf.placeholder("float")
b = tf.placeholder("float")

y = tf.multiply(a,b)
z = tf.add(y,y)

sess = tf.Session()
print(sess.run(z,feed_dict={a:1,b:1}))

2.0


In [4]:
#문제 7. zero와 숫자 1을 채워넣는 배열을 생성하시오 !

#1. numpy
import numpy as np

a = np.zeros((2, 2))
b = np.ones((2, 2))
print(a)
print(b)

#2. tensorflow

import tensorflow as tf

a = tf.zeros((2, 2))
b = tf.ones((2, 2))

sess = tf.Session()
print(sess.run(a))
print(sess.run(b))

sess.close()

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


In [12]:
#문제 8. 아래의 numpy문법을 tensorflow로 구현하시오 !

#1. numpy
import numpy as np

a = np.array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0])
print(np.argmax(a, axis = 0))

#2. tensorflow
import numpy as np
import tensorflow as tf

a = np.array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0])
b = tf.argmax(a, axis=0)

sess = tf.Session()
print(sess.run(b))
sess.close()

3
3


In [17]:
#문제 9. 아래의 numpy문법을 텐서 플로우로 구현하시오 !

#1. numpy

import  tensorflow  as  tf
import  numpy  as  np

a = np.array([[[1, 2, 3],
               [2, 1, 4],
               [5, 2, 1],
               [6, 3, 2]],
              [[5, 1, 3],
               [1, 3, 4],
               [4, 2, 6],
               [3, 9, 3]],
              [[4, 5, 6],
               [7, 4, 3],
               [2, 1, 5],
               [4, 3, 1]]])

print  ( np.sum( a, axis = 0) )


#2. tensorflow

import  tensorflow  as  tf
import  numpy  as  np

a = np.array([[[1, 2, 3],
               [2, 1, 4],
               [5, 2, 1],
               [6, 3, 2]],
              [[5, 1, 3],
               [1, 3, 4],
               [4, 2, 6],
               [3, 9, 3]],
              [[4, 5, 6],
               [7, 4, 3],
               [2, 1, 5],
               [4, 3, 1]]])
b = tf.reduce_sum(a, reduction_indices = [0])

sess = tf.Session()
print(sess.run(b))
sess.close()

[[10  8 12]
 [10  8 11]
 [11  5 12]
 [13 15  6]]
[[10  8 12]
 [10  8 11]
 [11  5 12]
 [13 15  6]]


In [22]:
#문제 10. 아래의 numnpy문법을 tensorflow로 구현하시오 !

#1. numpy
import numpy as np

a = np.array([i for i in range(144)])
b = a.reshape(12,12)
print(b.shape)


#2. tensorflow
import tensorflow as tf
import numpy as np

a = np.array([i for i in range(144)])
b = tf.reshape(a, (12, 12))

sess = tf.Session()
print(sess.run(b))
print(b.get_shape())

sess.close()

(12, 12)
[[  0   1   2   3   4   5   6   7   8   9  10  11]
 [ 12  13  14  15  16  17  18  19  20  21  22  23]
 [ 24  25  26  27  28  29  30  31  32  33  34  35]
 [ 36  37  38  39  40  41  42  43  44  45  46  47]
 [ 48  49  50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71]
 [ 72  73  74  75  76  77  78  79  80  81  82  83]
 [ 84  85  86  87  88  89  90  91  92  93  94  95]
 [ 96  97  98  99 100 101 102 103 104 105 106 107]
 [108 109 110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131]
 [132 133 134 135 136 137 138 139 140 141 142 143]]
(12, 12)


In [26]:
#문제 11. (텐서 플로우로 구현한 단층 신경망 이해에 중요 문법) 아래의 numpy배열의 열단위 sum을 출력하시오 !

#1. numpy
import numpy as np
import tensorflow as tf

x = np.arange(6).reshape(2, 3)
print(np.sum(x, axis=0))


#2. tensor
import numpy as np
import tensorflow as tf

x = np.arange(6)
y = tf.reshape(x, (2, 3))
z = tf.reduce_sum(y, reduction_indices = [0])

sess = tf.Session()
print(sess.run(z))

sess.close()

[3 5 7]
[3 5 7]


In [32]:
#문제 12. (텐서 플로우로 구현한 단층 신경망 이해에 중요 문법) 아래의 두 행렬의 합을 tensorflow로 구현하시오 !

#  0 0 0 + 1 1 1  =  1 1 1
#  0 0 0   1 1 1     1 1 1

import tensorflow as tf

a = tf.zeros([2, 3])
b = tf.ones([2, 3])
result = tf.add(a, b)

sess = tf.Session()

print(sess.run(a))
print(sess.run(b))
print(sess.run(result))
sess.close()

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [39]:
#문제 13. 아래의 행렬의 내적을 tensoflow로 구현하시오 !

# 2 2 2  ◎  3 3      
# 2 2 2      3 3  =  ?
#            3 3 

import tensorflow as tf
import numpy as np

x = tf.placeholder("float", [2, 3])
y = tf.placeholder("float", [3, 2])
result = tf.matmul(x, y)

sess = tf.Session()

print(sess.run(result, feed_dict = {x : [[2,2,2],[2,2,2,]],
                                    y : [[3,3],[3,3],[3,3]]}))
sess.close()

[[18. 18.]
 [18. 18.]]


In [44]:
#문제 14. (tensorflow의 cast함수의 이해) 아래의 배열의 True를 1로 변경하고 False를 0으로 변경시키시오 !

import tensorflow as tf

correct_prediction = [ True, False , True  ,True  ,True  ,True  ,True,  True  ,True  ,True  ,True  ,True
  ,True  ,True  ,True, False , True  ,True, False , True  ,True  ,True  ,True  ,True
  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True
  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True,
  True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True
  ,True  ,True  ,True  ,True  ,True  ,True ,False , True  ,True  ,True  ,True  ,True
  ,True  ,True, False , True, False , True  ,True  ,True  ,True  ,True  ,True  ,True
  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True
 ,False , True  ,True  ,True]

sess = tf.Session()

a = tf.cast(correct_prediction,"float")

print(sess.run(a))
sess.close()

[1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1.
 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 0. 1. 1. 1.]


In [46]:
#문제 15. 위의 출력된 결과에서 전체 갯수 중에 1이 몇개나 되는지 정확도를 출력하시오 1
#전체 다 더해서 전체 갯수로 나눈 값을 아래와 같이 출력하시오 !

import tensorflow as tf

correct_prediction = [ True, False , True  ,True  ,True  ,True  ,True,  True  ,True  ,True  ,True  ,True
  ,True  ,True  ,True, False , True  ,True, False , True  ,True  ,True  ,True  ,True
  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True
  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True,
  True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True
  ,True  ,True  ,True  ,True  ,True  ,True ,False , True  ,True  ,True  ,True  ,True
  ,True  ,True, False , True, False , True  ,True  ,True  ,True  ,True  ,True  ,True
  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True  ,True
 ,False , True  ,True  ,True]

sess = tf.Session()

a = tf.cast(correct_prediction,"float")
b = tf.reduce_mean(a)

print(sess.run(b))
sess.close()

0.93


In [49]:
#문제 16. Tensorflow에 기본적으로 내장되어 있는 mnist데이터를 가져오시오 !

import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)
batch_xs, batch_ys = mnist.train.next_batch(100)

print(batch_xs.shape)
print(batch_ys.shape)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
(100, 784)
(100, 10)


In [54]:
#문제 17. 위의 mnist 데이터 중에 train데이터의 라벨을 one hot encoding하지 말고 숫자로 100개의 라벨을 가져오시오 !

import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_data/")
batch_xs, batch_ys = mnist.train.next_batch(100)

print(batch_xs.shape)
print(batch_ys)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
(100, 784)
[8 1 8 5 0 5 0 9 1 0 8 3 2 5 5 8 5 2 6 2 4 5 2 3 6 7 2 1 6 0 5 8 5 9 1 4 5
 7 1 2 9 6 8 9 0 6 6 4 7 8 2 6 2 2 2 4 5 6 8 0 9 2 6 1 1 0 5 7 5 4 1 0 2 1
 0 6 7 7 6 7 2 3 4 5 2 7 8 2 4 9 5 3 4 8 7 7 7 3 3 7]


In [55]:
#문제 18. 이번에는 test데이터와 test 데이터의 라벨을 100개를 가져오는데 shape만 출력하시오 !

import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)
batch_xs, batch_ys = mnist.test.next_batch(100)

print(batch_xs.shape)
print(batch_ys.shape)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
(100, 784)
(100, 10)


In [59]:
#문제 19. 숫자 2로 채워진 행렬 2x3행렬을 텐서 플로우로 출력하시오 !

import tensorflow as tf

a = tf.placeholder("float",[2, 3])

sess = tf.Session()

print(sess.run(a, feed_dict = {a : [[2, 2, 2], [2, 2, 2]]}))

[[2. 2. 2.]
 [2. 2. 2.]]


In [64]:
# ----아래와 같이 숫자 2를 None으로 바꿔서 실행해 보시오 !

import tensorflow as tf

a = tf.placeholder("float",[None, 3])

sess = tf.Session()

print(sess.run(a, feed_dict = {a : [[2, 2, 2], [2, 2, 2], [2, 2, 2]]}))

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [67]:
#문제 20. Mnist 데이터 784(28x28)개에 맞게 x 변수를 placeholder로 선언하고 배치로 입력될 데이터의 갯수는 몇개이든 상관없게 None으로 변수를 만들고 Mnist데이터를 x변수에 100개를 담고 출력해 보시오 !

import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

x = tf.placeholder("float", [None,784])
batch_xs, batch_ys = mnist.test.next_batch(100)

sess = tf.Session()
print(sess.run(x, feed_dict = {x : batch_xs}).shape)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
(100, 784)


In [69]:
#문제 21. 위의 코드를 수정해서 훈련데이터 100개 뿐만 아니라 훈련데이터 라벨 100개도 출력되게끔 코드를 추가하시오 !

import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

x = tf.placeholder("float", [None,784])
y = tf.placeholder("float", [None, 10])
batch_xs, batch_ys = mnist.test.next_batch(100)

sess = tf.Session()
print(sess.run(x, feed_dict = {x : batch_xs}).shape)
print(sess.run(y, feed_dict = {y : batch_ys}).shape)
sess.close()

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
(100, 784)
(100, 10)


In [80]:
#문제 22. (텐서 플로우로 가중치를 랜점으로 생성하는 방법) 2x3행렬로 -1에서 1사이의 난수를 생성하는 변수 W를 생성하고 안의 내용을 확인하시오 !

import tensorflow as tf

W = tf.Variable(tf.random_uniform([2,3], -1, 1))

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
print(sess.run(W))
sess.close()

[[-0.42522287 -0.67010736  0.5873139 ]
 [ 0.4402938   0.93929124 -0.42909193]]


In [81]:
#문제 23. 이번에는 mnist데이터에 맞게 100x784와 내적할 가중치 행렬 784x50으로 W를 생성하시오 !

import tensorflow as tf

W = tf.Variable(tf.random_uniform([784,50], -1, 1))
init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
print(sess.run(W))
sess.close()

[[ 0.8730664  -0.30416036  0.66695786 ...  0.6086316   0.8780179
   0.20683146]
 [ 0.37305593 -0.29965925  0.5444367  ... -0.51300645  0.2886641
  -0.70930123]
 [ 0.6806414   0.27309847 -0.8303399  ... -0.04883766 -0.62420106
   0.2734213 ]
 ...
 [ 0.65482545  0.54221654  0.6222713  ... -0.02185154  0.37688255
  -0.13368821]
 [ 0.9844551  -0.4754796   0.47851062 ...  0.8492763   0.1808443
   0.05456066]
 [ 0.0249536   0.51436925 -0.25743175 ...  0.05058217 -0.46639585
   0.01495862]]


In [86]:
#문제 24. 위에서 만든 입력값 (문제21) 100x784와 지금 만든 가중치 785x50행렬과 내적을 한 결과를 출력하시오 !

import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

x = tf.placeholder("float", [None,784])
W = tf.Variable(tf.random_uniform([784,50], -1, 1))
batch_xs, batch_ys = mnist.test.next_batch(100)
init = tf.global_variables_initializer()
z = tf.matmul(x, W)

sess = tf.Session()
sess.run(init)
print(sess.run(z, feed_dict = {x : batch_xs}).shape)
sess.close()

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
(100, 50)


In [88]:
#문제 25. 1x50으로 bias를 생성하는데 변수 b로 생성하고 숫자를 다 1로 채우시오 !

import tensorflow as tf

b = tf.Variable(tf.ones([50]))
init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
print(sess.run(b))
sess.close()

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1.]


In [90]:
#문제 26. 문제 24번에서 구한 두 행렬의 내적과 지금 방금 생성한 바이어스의 합을 출력하시오 !

import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

x = tf.placeholder("float", [None,784])
W = tf.Variable(tf.random_uniform([784,50], -1, 1))
b = tf.Variable(tf.ones([50]))
y = tf.matmul(x, W) + b
batch_xs, batch_ys = mnist.test.next_batch(100)
init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
print(sess.run(y, feed_dict = {x : batch_xs}).shape)
sess.close()

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
(100, 50)


In [91]:
#문제 27. 문제 26번에서 구한 가중의 합인 y값을 시그모이드 함수에 입력해서 출력한 결과를 출력하시오 !

import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

x = tf.placeholder("float", [None,784])
W = tf.Variable(tf.random_uniform([784,50], -1, 1))
b = tf.Variable(tf.ones([50]))
y = tf.matmul(x, W) + b
y_hat = tf.nn.sigmoid(y)
batch_xs, batch_ys = mnist.test.next_batch(100)
init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
print(sess.run(y_hat, feed_dict = {x : batch_xs}).shape)
sess.close()

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
(100, 50)


In [92]:
#문제 28. 위의 활성화 함수를 Relu로 변경하시오 !

import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

x = tf.placeholder("float", [None,784])
W = tf.Variable(tf.random_uniform([784,50], -1, 1))
b = tf.Variable(tf.ones([50]))
y = tf.matmul(x, W) + b
y_hat = tf.nn.relu(y)
batch_xs, batch_ys = mnist.test.next_batch(100)
init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
print(sess.run(y_hat, feed_dict = {x : batch_xs}).shape)
sess.close()

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
(100, 50)


In [94]:
#문제 29. 이번에는 Relu가 아니라 가중의 합인 y_hat을 softmax 함수를 통과시킨 결과가 어떻게 되는지 확인하시오 !
#(10개짜리 확률벡터 100개 출력이 예상됨)

import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

x = tf.placeholder("float", [None,784])
W = tf.Variable(tf.random_uniform([784,10], -1, 1))
b = tf.Variable(tf.ones([10]))
y = tf.matmul(x, W) + b
y_hat = tf.nn.softmax(y)
batch_xs, batch_ys = mnist.test.next_batch(100)
init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
print(sess.run(y_hat, feed_dict = {x : batch_xs}).shape)
sess.close()

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
(100, 10)


In [96]:
#문제 30. 텐서 플로우의 argmax 함수를 이용해서 위에서 출력된 100x10확률벡터들의 최대값의 인덱스 번호를 100개 출력하시오 !

import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

x = tf.placeholder("float", [None,784])
W = tf.Variable(tf.random_uniform([784,10], -1, 1))
b = tf.Variable(tf.ones([10]))
y = tf.matmul(x, W) + b
y_hat = tf.nn.softmax(y)
y_predict = tf.argmax(y_hat, axis = 1)
batch_xs, batch_ys = mnist.test.next_batch(100)
init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
print(sess.run(y_predict, feed_dict = {x : batch_xs}))
sess.close()

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
[4 2 1 2 2 3 2 1 1 2 2 4 4 2 2 8 2 2 4 2 1 1 2 2 4 4 2 4 2 2 1 1 4 4 1 2 2
 1 2 6 2 7 1 4 2 2 8 4 2 2 8 4 2 2 1 7 2 4 2 2 1 4 1 4 2 4 1 6 2 6 2 8 1 4
 2 6 4 4 1 2 2 1 2 2 2 1 4 2 1 2 4 2 2 1 9 2 4 1 2 2]


In [107]:
#문제 31. 위의 코드에 라벨을 가져오는 코드를 추가해서 정확도를 출력하시오 !
#(위의 예상 숫자 100개와 실제 숫자 100개를 비교)

import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

x = tf.placeholder("float", [None,784])
y_onehot = tf.placeholder("float", [None, 10])
y_label = tf.argmax(y_onehot, axis = 1)
W = tf.Variable(tf.random_uniform([784,10], -1, 1))
b = tf.Variable(tf.ones([10]))
y = tf.matmul(x, W) + b
y_hat = tf.nn.softmax(y)
y_predict = tf.argmax(y_hat, axis = 1)
correction_prediction = tf.equal(y_predict, y_label)
accuracy = tf.reduce_mean(tf.cast(correction_prediction, "float"))

batch_xs, batch_ys = mnist.test.next_batch(100)
init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
print(sess.run(accuracy, feed_dict = {x : batch_xs, y_onehot: batch_ys}))
sess.close()

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
0.13


In [109]:
#문제 32. 문제 31번 코드에 오차함수인 교차 엔트로피 함수를 추가하고 loss를 출력하시오 !

import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

x = tf.placeholder("float", [None,784])
y_onehot = tf.placeholder("float", [None, 10])
# y_label = tf.argmax(y_onehot, axis = 1)
W = tf.Variable(tf.random_uniform([784,10], -1, 1))
b = tf.Variable(tf.ones([10]))
y = tf.matmul(x, W) + b
y_hat = tf.nn.softmax(y)
y_predict = tf.argmax(y_hat, axis = 1)
# correction_prediction = tf.equal(y_predict, y_label)
# accuracy = tf.reduce_mean(tf.cast(correction_prediction, "float"))
loss = - tf.reduce_sum(y_onehot*tf.log(y_hat), axis = 1)

batch_xs, batch_ys = mnist.test.next_batch(100)
init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
print(sess.run(loss, feed_dict = {x : batch_xs, y_onehot: batch_ys}).shape)
sess.close()

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
(100,)


In [113]:
#문제 33. 지금까지 만든 코드에 Adam 경사감소법 코드를 추가해서 학습이 되게 하시오 1

import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

x = tf.placeholder("float", [None,784])
y_onehot = tf.placeholder("float", [None, 10])
y_label = tf.argmax(y_onehot, axis = 1)
W = tf.Variable(tf.random_uniform([784,10], -1, 1))
b = tf.Variable(tf.ones([10]))
y = tf.matmul(x, W) + b
y_hat = tf.nn.softmax(y)
y_predict = tf.argmax(y_hat, axis = 1)
correction_prediction = tf.equal(y_predict, y_label)
accuracy = tf.reduce_mean(tf.cast(correction_prediction, "float"))
loss = - tf.reduce_sum(y_onehot*tf.log(y_hat), axis = 1)
optimizer = tf.train.AdamOptimizer(learning_rate=0.01)
train = optimizer.minimize(loss)

batch_xs, batch_ys = mnist.test.next_batch(100)
init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
sess.run(train, feed_dict = {x : batch_xs, y_onehot: batch_ys})
print(sess.run(accuracy, feed_dict = {x : batch_xs, y_onehot : batch_ys}))
sess.close()

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
0.09


In [124]:
#문제 34. 위의 코드에 for loop문을 이용해서 1에폭 돌게 구성하시오 !

import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

x = tf.placeholder("float", [None,784])
y_onehot = tf.placeholder("float", [None, 10])
y_label = tf.argmax(y_onehot, axis = 1)
W = tf.Variable(tf.random_uniform([784,10], -1, 1))
b = tf.Variable(tf.ones([10]))
y = tf.matmul(x, W) + b
y_hat = tf.nn.softmax(y)
y_predict = tf.argmax(y_hat, axis = 1)
correction_prediction = tf.equal(y_predict, y_label)
accuracy = tf.reduce_mean(tf.cast(correction_prediction, "float"))
loss = - tf.reduce_sum(y_onehot*tf.log(y_hat), axis = 1)
optimizer = tf.train.AdamOptimizer(learning_rate=0.01)
train = optimizer.minimize(loss)

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
for i in range(1, 601):
    batch_xs, batch_ys = mnist.test.next_batch(100)
    sess.run(train, feed_dict = {x : batch_xs, y_onehot: batch_ys})
print(sess.run(accuracy, feed_dict = {x : batch_xs, y_onehot : batch_ys}))
sess.close()

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
0.96


In [128]:
#문제 35. 위의 코드를 수정해서 아래와 같이 결과가 출력되게 하시오 ! (오늘의 마지막 문제)

import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

x = tf.placeholder("float", [None,784])
y_onehot = tf.placeholder("float", [None, 10])
y_label = tf.argmax(y_onehot, axis = 1)
W = tf.Variable(tf.random_uniform([784,10], -1, 1))
b = tf.Variable(tf.ones([10]))
y = tf.matmul(x, W) + b
y_hat = tf.nn.softmax(y)
y_predict = tf.argmax(y_hat, axis = 1)
correction_prediction = tf.equal(y_predict, y_label)
accuracy = tf.reduce_mean(tf.cast(correction_prediction, "float"))
loss = - tf.reduce_sum(y_onehot*tf.log(y_hat), axis = 1)
optimizer = tf.train.AdamOptimizer(learning_rate=0.01)
train = optimizer.minimize(loss)

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
for i in range(1, 4):
    for j in range(1, 601):
        batch_xs, batch_ys = mnist.test.next_batch(100)
        sess.run(train, feed_dict = {x : batch_xs, y_onehot: batch_ys})
    print('%d 에폭 정확도'%i, sess.run(accuracy, feed_dict = {x : batch_xs, y_onehot : batch_ys}))

sess.close()

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
1 에폭 정확도 0.95
2 에폭 정확도 0.98
3 에폭 정확도 0.96
