In [ ]:
import os
import numpy as np
import cv2

test_image = "c:\\a\\cifar10\\test"

def image_load(path):
    file_list = os.listdir(path)
    for i in range(len(file_list)):
        file_list[i] = int(file_list[i][:-4])
    file_list.sort()
    for i in range(len(file_list)):
        file_list[i] = path + "\\" + str(file_list[i]) + ".png"
    image =[]
    for i in file_list:
        img = cv2.imread(i)
        image.append(img)
    image = np.array(image)
    return image
    
print(image_load(test_image).shape)

In [6]:
#문제 52. test_label.csv 파일을 J:\\a\\cifar10 밑에 복사하고 결과가 아래와 같이 출력될 수 있도록 함수를 생성하시오

test_image = "c:\\a\\cifar10\\test"
test_label = "c:\\a\\cifar10\\test_label.csv"

import os
import numpy as np
import csv

def label_load(path):
    file = open(path)
    labeldata = csv.reader(file)
    labellist = []
    for i in labeldata:
        labellist.append(i)
    return labellist
print( label_load(test_label) )

[['3'], ['8'], ['8'], ['0'], ['6'], ['6'], ['1'], ['6'], ['3'], ['1'], ['0'], ['9'], ['5'], ['7'], ['9'], ['8'], ['5'], ['7'], ['8'], ['6'], ['7'], ['0'], ['4'], ['9'], ['5'], ['2'], ['4'], ['0'], ['9'], ['6'], ['6'], ['5'], ['4'], ['5'], ['9'], ['2'], ['4'], ['1'], ['9'], ['5'], ['4'], ['6'], ['5'], ['6'], ['0'], ['9'], ['3'], ['9'], ['7'], ['6'], ['9'], ['8'], ['0'], ['3'], ['8'], ['8'], ['7'], ['7'], ['4'], ['6'], ['7'], ['3'], ['6'], ['3'], ['6'], ['2'], ['1'], ['2'], ['3'], ['7'], ['2'], ['6'], ['8'], ['8'], ['0'], ['2'], ['9'], ['3'], ['3'], ['8'], ['8'], ['1'], ['1'], ['7'], ['2'], ['5'], ['2'], ['7'], ['8'], ['9'], ['0'], ['3'], ['8'], ['6'], ['4'], ['6'], ['6'], ['0'], ['0'], ['7'], ['4'], ['5'], ['6'], ['3'], ['1'], ['1'], ['3'], ['6'], ['8'], ['7'], ['4'], ['0'], ['6'], ['2'], ['1'], ['3'], ['0'], ['4'], ['2'], ['7'], ['8'], ['3'], ['1'], ['2'], ['8'], ['0'], ['8'], ['3'], ['5'], ['2'], ['4'], ['1'], ['8'], ['9'], ['1'], ['2'], ['9'], ['7'], ['2'], ['9'], ['6'], ['5'], ['6']

In [9]:
#문제 53. 위의 숫자 list 를 numpy 배열로 변환하시오 !

test_image = "c:\\a\\cifar10\\test"
test_label = "c:\\a\\cifar10\\test_label.csv"

import os
import numpy as np
import csv

def label_load(path):
    file = open(path)
    labeldata = csv.reader(file)
    labellist = []
    for i in labeldata:
        labellist.append(i)
    labellist = np.array(labellist)
    return labellist

print( label_load(test_label) )

[['3']
 ['8']
 ['8']
 ...
 ['5']
 ['1']
 ['7']]


In [11]:
#문제 54. 위의 결과가 문자가 아니라 숫자로 출력되게 변환하시오 !


test_image = "c:\\a\\cifar10\\test"
test_label = "c:\\a\\cifar10\\test_label.csv"

import os
import numpy as np
import csv

def label_load(path):
    file = open(path)
    labeldata = csv.reader(file)
    labellist = []
    for i in labeldata:
        labellist.append(i)
    labellist = np.array(labellist).astype(int)
    return labellist

print( label_load(test_label) )

[[3]
 [8]
 [8]
 ...
 [5]
 [1]
 [7]]


In [12]:
#문제 55. 아래의 결과를 출력하시오 !

import numpy as np

print(np.eye(10)[4])

[[3]
 [8]
 [8]
 ...
 [5]
 [1]
 [7]]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [20]:
#문제 56. 문제 54번에서 가져온 숫자리스트를 가지고 아래와 같이 one hot encoding된 결과를 출력하시오 !

test_image = "c:\\a\\cifar10\\test"
test_label = "c:\\a\\cifar10\\test_label.csv"

import os
import numpy as np
import csv

def label_load(path):
    file = open(path)
    labeldata = csv.reader(file)
    labellist = []
    for i in labeldata:
        labellist.append(i)
    labellist = np.array(labellist).astype(int)
    labellist = np.eye(10)[labellist]
    return labellist

print( label_load(test_label))

[[[0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 1. 0.]]

 [[0. 0. 0. ... 0. 1. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]]

 [[0. 1. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 1. 0. 0.]]]


In [23]:
#문제 57. 위의 차원은 3차원인데 우리는 2차원으로 줄여야 한다. 왜냐하면 cnn코드에서 라벨이 입력될 때는 아래처럼 2차원이기 때문이다.

test_image = "c:\\a\\cifar10\\test"
test_label = "c:\\a\\cifar10\\test_label.csv"

import os
import numpy as np
import csv

def label_load(path):
    file = open(path)
    labeldata = csv.reader(file)
    labellist = []
    for i in labeldata:
        labellist.append(i)
    labellist = np.array(labellist).astype(int)
    labellist = np.eye(10)[labellist]
    return np.squeeze(labellist, axis = 1)

print( label_load(test_label).shape )

(10000, 10)


In [30]:
#문제 58. 지금까지 만든 두가지 함수 image_load,label_load를 loader2.py라는 파이썬 코드에 저장하고 아래와 같이 loader2.py를 import 한후에 cifar10전체 데이터를 로드하는 코드를 구현하시오 !

import  loader2
import time

train_image = 'c:\\a\\cifar10\\train\\'
train_label = 'c:\\a\\cifar10\\train_label.csv'
test_image = 'c:\\a\\cifar10\\test\\'
test_label = 'c:\\a\\cifar10\\test_label.csv'

print("LOADING DATA")
start = time.time()
trainX = loader2.image_load(train_image)
print(trainX.shape) # (50000, 32, 32,3)
trainY = loader2.label_load(train_label)
print(trainY.shape) # (50000, 10)
testX = loader2.image_load(test_image)
print(testX.shape) # (10000,32, 32, 3)
testY = loader2.label_load(test_label)
print(testY.shape) # (10000, 10)

LOADING DATA
(50000, 32, 32, 3)
(50000, 10)
(10000, 32, 32, 3)
(10000, 10)


In [32]:
#문제 59. test100폴더 밑에 10000개의 데이터중 100개만 출력하시오 !

import os
import numpy as np
import csv
import loader2

test_image='c:\\a\\cifar10\\test'
trainX=loader2.image_load(test_image)

print(trainX[0:100])
print(trainX[100:200])

[[[[ 49 112 158]
   [ 47 111 159]
   [ 51 116 165]
   ...
   [ 36  95 137]
   [ 36  91 126]
   [ 33  85 116]]

  [[ 51 112 152]
   [ 40 110 151]
   [ 45 114 159]
   ...
   [ 31  95 136]
   [ 32  91 125]
   [ 34  88 119]]

  [[ 47 110 151]
   [ 33 109 151]
   [ 36 111 158]
   ...
   [ 34  98 139]
   [ 34  95 130]
   [ 33  89 120]]

  ...

  [[177 124  68]
   [148 100  42]
   [137  88  31]
   ...
   [146  97  38]
   [108  64  13]
   [127  85  40]]

  [[168 116  61]
   [148 102  49]
   [132  85  35]
   ...
   [130  82  26]
   [126  82  29]
   [107  64  20]]

  [[160 107  54]
   [149 105  56]
   [132  89  45]
   ...
   [124  77  24]
   [129  84  34]
   [110  67  21]]]


 [[[235 235 235]
   [231 231 231]
   [232 232 232]
   ...
   [233 233 233]
   [233 233 233]
   [232 232 232]]

  [[238 238 238]
   [235 235 235]
   [235 235 235]
   ...
   [236 236 236]
   [236 236 236]
   [235 235 235]]

  [[237 237 237]
   [234 234 234]
   [234 234 234]
   ...
   [235 235 235]
   [235 235 235]
   [234 234

In [34]:
#문제 60. next_batch함수를 만들어서 아래와 같이 데이터를 입력하고 함수를 실행하면 trainX에서 100개의 데이터(numpy 배열)을 가져오게 하시오 !

import os
import numpy as np
import csv
import loader2

test_image='c:\\a\\cifar10\\test'
trainX=loader2.image_load(test_image)

def next_batch(img, start, finish):
    return img[start:finish]

print(next_batch(trainX, 0, 100).shape)

(100, 32, 32, 3)


In [38]:
#문제 61. 이번에는 라벨도 배치 사이즈 만큼 같이 출력될 수 있도록 next_batch함수에 코드를 추가해서 아래와 같이 출력되게 하시오 !

import os
import numpy as np
import csv
import loader2

def next_batch(img, label, start, finish):
    return img[start:finish], label[start:finish]

train_image = 'c:\\a\\cifar10\\train\\'
train_label = 'c:\\a\\cifar10\\train_label.csv'
test_image = 'c:\\a\\cifar10\\test\\'
test_label = 'c:\\a\\cifar10\\test_label.csv'

print("LOADING DATA")
trainX = loader2.image_load(train_image)
trainY = loader2.label_load(train_label)

x, y = next_batch(trainX, trainY, 0, 100)
print(x)
print(y)

LOADING DATA
[[[[ 63  62  59]
   [ 45  46  43]
   [ 43  48  50]
   ...
   [108 132 158]
   [102 125 152]
   [103 124 148]]

  [[ 20  20  16]
   [  0   0   0]
   [  0   8  18]
   ...
   [ 55  88 123]
   [ 50  83 119]
   [ 57  87 122]]

  [[ 21  24  25]
   [  0   7  16]
   [  8  27  49]
   ...
   [ 50  84 118]
   [ 50  84 120]
   [ 42  73 109]]

  ...

  [[ 96 170 208]
   [ 34 153 201]
   [ 26 161 198]
   ...
   [ 70 133 160]
   [  7  31  56]
   [ 20  34  53]]

  [[ 96 139 180]
   [ 42 123 173]
   [ 30 144 186]
   ...
   [ 94 148 184]
   [ 34  62  97]
   [ 34  53  83]]

  [[116 144 177]
   [ 94 129 168]
   [ 87 142 179]
   ...
   [140 184 216]
   [ 84 118 151]
   [ 72  92 123]]]


 [[[187 177 154]
   [136 137 126]
   [ 95 104 105]
   ...
   [ 71  95  91]
   [ 71  90  87]
   [ 70  81  79]]

  [[169 160 140]
   [154 153 145]
   [118 125 125]
   ...
   [ 78  99  96]
   [ 62  80  77]
   [ 61  73  71]]

  [[164 155 140]
   [149 146 139]
   [112 115 115]
   ...
   [ 64  82  79]
   [ 55  70  68

In [40]:
#문제 62. 아래의 코드를 실행해 보시오 !

import random
import numpy as np
print( np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [56]:
#문제 63. 위의 숫자 10개가 랜덤으로 섞여서 출력되게 하시오 !
#(random.shuffle을 사용해서 구현하시오 !)

import random
import numpy as np
x = np.arange(10)
random.shuffle(x)
print(x)

[4 2 6 8 7 0 9 1 5 3]


In [5]:
#문제 64. 위의 코드를 이용해서 shuffle_batch함수를 만들어서 입력된 데이터가 shuffle되게 하시오 !

# import random
import numpy as np
import  loader2


train_image = 'c:\\a\\cifar10\\train\\'
train_label = 'c:\\a\\cifar10\\train_label.csv'
test_image = 'c:\\a\\cifar10\\test\\'
test_label = 'c:\\a\\cifar10\\test_label.csv'

print("LOADING DATA")
testX = loader2.image_load(test_image)
testY = loader2.label_load(test_label)
print(testX)
print(testY)


def shuffle_batch(dataa, datab):
    x = np.arange(len(dataa))
    np.random.shuffle(x)
    data_list2 = dataa[x]
    label2 = datab[x]
    return data_list2, label2

x, y = shuffle_batch(testX, testY)
print(x.shape)
print(y.shape)

LOADING DATA
[[[[ 49 112 158]
   [ 47 111 159]
   [ 51 116 165]
   ...
   [ 36  95 137]
   [ 36  91 126]
   [ 33  85 116]]

  [[ 51 112 152]
   [ 40 110 151]
   [ 45 114 159]
   ...
   [ 31  95 136]
   [ 32  91 125]
   [ 34  88 119]]

  [[ 47 110 151]
   [ 33 109 151]
   [ 36 111 158]
   ...
   [ 34  98 139]
   [ 34  95 130]
   [ 33  89 120]]

  ...

  [[177 124  68]
   [148 100  42]
   [137  88  31]
   ...
   [146  97  38]
   [108  64  13]
   [127  85  40]]

  [[168 116  61]
   [148 102  49]
   [132  85  35]
   ...
   [130  82  26]
   [126  82  29]
   [107  64  20]]

  [[160 107  54]
   [149 105  56]
   [132  89  45]
   ...
   [124  77  24]
   [129  84  34]
   [110  67  21]]]


 [[[235 235 235]
   [231 231 231]
   [232 232 232]
   ...
   [233 233 233]
   [233 233 233]
   [232 232 232]]

  [[238 238 238]
   [235 235 235]
   [235 235 235]
   ...
   [236 236 236]
   [236 236 236]
   [235 235 235]]

  [[237 237 237]
   [234 234 234]
   [234 234 234]
   ...
   [235 235 235]
   [235 235 235

In [96]:
import os
import numpy as np
import cv2
import csv
import random

train_image = 'c:\\a\\cifar10\\train\\'
train_label = 'c:\\a\\cifar10\\train_label.csv'
test_image = 'c:\\a\\cifar10\\test\\'
test_label = 'c:\\a\\cifar10\\test_label.csv'

trainX = loader2.image_load(train_image)
trainY = loader2.label_load(train_label)
testX = loader2.image_load(test_image)
testY = loader2.label_load(test_label)

trainX, trainY = loader2.shuffle_batch(trainX, trainY)
testX, testY = loader2.shuffle_batch(testX, testY)


def image_load(path):
    file_list = os.listdir(path)
    for i in range(len(file_list)):
        file_list[i] = int(file_list[i][:-4])
    file_list.sort()
    for i in range(len(file_list)):
        file_list[i] = path + "\\" + str(file_list[i]) + ".png"
    image =[]
    for i in file_list:
        img = cv2.imread(i)
        image.append(img)
    image = np.array(image)
    return image

def label_load(path):
    file = open(path)
    labeldata = csv.reader(file)
    labellist = []
    for i in labeldata:
        labellist.append(i)
    labellist = np.array(labellist).astype(int)
    labellist = np.eye(10)[labellist]
    return np.squeeze(labellist, axis = 1)

def next_batch(img, label, start, finish):
    return img[start:finish], label[start:finish]

def shuffle_batch(dataa, datab):
    x = np.arange(len(dataa))
    np.random.shuffle(x)
    data_list2 = dataa[x]
    label2 = datab[x]
    return data_list2, label2

for i in range(1, 16):
    for j in range(1, 601):
        batch_range_st = (j-1)*100
        batch_range_fi = j*100
        train_xs, train_ys = loader2.next_batch(trainX, traixY, batch_range_st, batch_range_fi)
        test_xs, test_ys = loader2.next_batch(testX, testY, batch_range_st, batch_range_fi)

In [1]:
#문제 65. 기존 mnist 데이터를 텐써 플로우로 만든 cnn신경망에 입력하는 코드를 가져와서 mnist 대신에 cifar10 데이터를 입력해서 학습 시키고 정확도 그래프를 볼 수 있도록 코드를 완성시키시오.

import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
import matplotlib.pyplot as plt
import numpy as np
import loader2

#데이터 로드 그리고 한번에 셔플
train_image = 'c:\\a\\cifar10\\train\\'
train_label = 'c:\\a\\cifar10\\train_label.csv'
test_image = 'c:\\a\\cifar10\\test\\'
test_label = 'c:\\a\\cifar10\\test_label.csv'

print("LOADING DATA")
trainX = loader2.image_load(train_image)
trainY = loader2.label_load(train_label)
testX = loader2.image_load(test_image)
testY = loader2.label_load(test_label)

trainX, trainY = loader2.shuffle_batch(trainX, trainY)
testX, testY = loader2.shuffle_batch(testX, testY)



# 입력층
tf.reset_default_graph()
x_load = tf.placeholder("float", [None, 32, 32, 3])
z_onehot = tf.placeholder("float", [None, 10])
z_label = tf.argmax(z_onehot, axis = 1)
keep_prob = tf.placeholder("float")



# 은닉 1층
W1 = tf.get_variable(name='W1', shape=[3, 3, 3, 32], \
                     initializer=tf.contrib.layers.variance_scaling_initializer())
b1 = tf.Variable(tf.ones([32, 32, 32]))

x = tf.nn.conv2d(x_load, W1, strides=[1, 1, 1, 1], padding = 'SAME')
x = tf.nn.relu(x) + b1
x = tf.nn.max_pool(x, ksize = [1, 2, 2, 1], strides = [1, 2, 2, 1], padding = 'SAME')
# x = tf.reshape(x, [-1, 6272])



# 은닉 2층
W2 = tf.get_variable(name='W2', shape=[3, 3, 32, 64], \
                     initializer=tf.contrib.layers.variance_scaling_initializer())
b2 = tf.Variable(tf.ones([16, 16, 64]))

x1 = tf.nn.conv2d(x, W2, strides=[1, 1, 1, 1], padding = 'SAME')
x1 = tf.nn.relu(x1) + b2
x1 = tf.nn.max_pool(x1, ksize = [1, 2, 2, 1], strides = [1, 2, 2, 1], padding = 'SAME')
x1 = tf.reshape(x1, [-1, 4096])



# 은닉 3층
W3 = tf.get_variable(name='W3', shape=[4096, 100], \
                     initializer=tf.contrib.layers.variance_scaling_initializer())
b3 = tf.Variable(tf.ones([100]))

y = tf.matmul(x1, W3) + b3
y = tf.contrib.layers.batch_norm(y,True)
y = tf.nn.relu(y)
y = tf.nn.dropout(y, keep_prob)



# 은닉 3층
W4 = tf.get_variable(name='W4', shape=[100, 100], \
                     initializer=tf.contrib.layers.variance_scaling_initializer())
b4 = tf.Variable(tf.ones([100]))

y1 = tf.matmul(y, W4) + b4
y1 = tf.nn.relu(y1)
y1 = tf.nn.dropout(y1, keep_prob)



# 출력층(4층)
W5 = tf.get_variable(name='W5', shape=[100, 10], \
                     initializer=tf.contrib.layers.variance_scaling_initializer())
b5 = tf.Variable(tf.ones([10]))

z = tf.matmul(y1, W5) + b5
z_hat = tf.nn.softmax(z)
z = tf.argmax(z_hat, axis = 1)



correction_prediction = tf.equal(z, z_label)
accuracy = tf.reduce_mean(tf.cast(correction_prediction, "float"))
loss = - tf.reduce_sum(z_onehot*tf.log(z_hat), axis = 1)
optimizer = tf.train.AdamOptimizer(learning_rate=0.001)
train = optimizer.minimize(loss)

init = tf.global_variables_initializer()



# 세션 활성화
sess = tf.Session()
sess.run(init)

print("start")
for i in range(1, 11):
    for j in range(1, 500):
        batch_range_st = (j-1)*100
        batch_range_fi = j*100
        train_xs, train_ys = loader2.next_batch(trainX, trainY, batch_range_st, batch_range_fi)
        sess.run(train, feed_dict = {x_load : train_xs, z_onehot: train_ys, keep_prob : 0.9})
    train_acc = sess.run(accuracy, \
                         feed_dict = {x_load : train_xs, z_onehot : train_ys, keep_prob : 1.0})
    print('train %d 에폭 정확도'%i, train_acc)
    test_xs, test_ys =loader2.next_batch(testX, testY, 0, 100)
    test_acc = sess.run(accuracy, \
                        feed_dict = {x_load : test_xs, z_onehot : test_ys, keep_prob : 1.0})
    print('test  %d 에폭 정확도'%i, test_acc)
    print('+=====================+')

sess.close()

LOADING DATA
start
train 1 에폭 정확도 0.71
test  1 에폭 정확도 0.67
+=====================+
train 2 에폭 정확도 0.74
test  2 에폭 정확도 0.68
+=====================+
train 3 에폭 정확도 0.79
test  3 에폭 정확도 0.73
+=====================+
train 4 에폭 정확도 0.82
test  4 에폭 정확도 0.67
+=====================+
train 5 에폭 정확도 0.82
test  5 에폭 정확도 0.66
+=====================+
train 6 에폭 정확도 0.9
test  6 에폭 정확도 0.67
+=====================+
train 7 에폭 정확도 0.94
test  7 에폭 정확도 0.66
+=====================+
train 8 에폭 정확도 0.97
test  8 에폭 정확도 0.68
+=====================+
train 9 에폭 정확도 0.94
test  9 에폭 정확도 0.71
+=====================+
train 10 에폭 정확도 0.94
test  10 에폭 정확도 0.69
+=====================+


In [ ]:
#문제 66. 기존 mnist 데이터를 텐써 플로우로 만든 cnn신경망에 입력하는 코드를 가져와서 mnist 대신에 cifar10 데이터를 입력해서 학습 시키고 정확도 그래프를 볼 수 있도록 코드를 완성시키시오.

import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
import matplotlib.pyplot as plt
import numpy as np
import loader2

#데이터 로드 그리고 한번에 셔플
train_image = 'c:\\a\\cifar10\\train\\'
train_label = 'c:\\a\\cifar10\\train_label.csv'
test_image = 'c:\\a\\cifar10\\test\\'
test_label = 'c:\\a\\cifar10\\test_label.csv'

print("LOADING DATA")
trainX = loader2.image_load(train_image)
trainY = loader2.label_load(train_label)
testX = loader2.image_load(test_image)
testY = loader2.label_load(test_label)

trainX, trainY = loader2.shuffle_batch(trainX, trainY)
testX, testY = loader2.shuffle_batch(testX, testY)



# 입력층
tf.reset_default_graph()
x_load = tf.placeholder("float", [None, 32, 32, 3])
z_onehot = tf.placeholder("float", [None, 10])
z_label = tf.argmax(z_onehot, axis = 1)
keep_prob = tf.placeholder("float")



# CNN 은닉 1층
W1 = tf.get_variable(name='W1', shape=[3, 3, 3, 128], \
                     initializer=tf.contrib.layers.variance_scaling_initializer())
b1 = tf.Variable(tf.ones([32, 32, 128]))
W2 = tf.get_variable(name='W2', shape=[3, 3, 128, 128], \
                     initializer=tf.contrib.layers.variance_scaling_initializer())
b2 = tf.Variable(tf.ones([32, 32, 128]))
x = tf.nn.conv2d(x_load, W1, strides=[1, 1, 1, 1], padding = 'SAME')
x = tf.nn.relu(x) + b1
x = tf.nn.conv2d(x, W2, strides=[1, 1, 1, 1], padding = 'SAME')
x = tf.nn.relu(x) + b2
x = tf.nn.max_pool(x, ksize = [1, 2, 2, 1], strides = [1, 2, 2, 1], padding = 'SAME')



# CNN 은닉 2층
W3 = tf.get_variable(name='W3', shape=[3, 3, 128, 256], \
                     initializer=tf.contrib.layers.variance_scaling_initializer())
b3 = tf.Variable(tf.ones([16, 16, 256]))
W4 = tf.get_variable(name='W4', shape=[3, 3, 256, 256], \
                     initializer=tf.contrib.layers.variance_scaling_initializer())
b4 = tf.Variable(tf.ones([16, 16, 256]))
x1 = tf.nn.conv2d(x, W3, strides=[1, 1, 1, 1], padding = 'SAME')
x1 = tf.nn.relu(x1) + b3
x1 = tf.nn.conv2d(x1, W4, strides=[1, 1, 1, 1], padding = 'SAME')
x1 = tf.nn.relu(x1) + b4
x1 = tf.nn.max_pool(x1, ksize = [1, 2, 2, 1], strides = [1, 2, 2, 1], padding = 'SAME')





# CNN 은닉 3층
W5 = tf.get_variable(name='W5', shape=[3, 3, 256, 512], \
                     initializer=tf.contrib.layers.variance_scaling_initializer())
b5 = tf.Variable(tf.ones([8, 8, 512]))
W6 = tf.get_variable(name='W6', shape=[3, 3, 512, 512], \
                     initializer=tf.contrib.layers.variance_scaling_initializer())
b6 = tf.Variable(tf.ones([8, 8, 512]))
x2 = tf.nn.conv2d(x1, W5, strides=[1, 1, 1, 1], padding = 'SAME')
x2 = tf.nn.relu(x2) + b5
x2 = tf.nn.conv2d(x2, W6, strides=[1, 1, 1, 1], padding = 'SAME')
x2 = tf.nn.relu(x2) + b6
x2 = tf.nn.max_pool(x2, ksize = [1, 2, 2, 1], strides = [1, 2, 2, 1], padding = 'SAME')
x2 = tf.reshape(x2, [-1, 8192])




# Linear 은닉 4층
W7 = tf.get_variable(name='W7', shape=[8192, 1024], \
                     initializer=tf.contrib.layers.variance_scaling_initializer())
b7 = tf.Variable(tf.ones([1024]))
y = tf.matmul(x2, W7) + b7
y = tf.contrib.layers.batch_norm(y,True)
y = tf.nn.relu(y)
y = tf.nn.dropout(y, keep_prob)




# Linear 은닉 5층
W8 = tf.get_variable(name='W8', shape=[1024, 1024], \
                     initializer=tf.contrib.layers.variance_scaling_initializer())
b8 = tf.Variable(tf.ones([1024]))
y1 = tf.matmul(y, W8) + b8
y1 = tf.contrib.layers.batch_norm(y1,True)
y1 = tf.nn.relu(y1)
y1 = tf.nn.dropout(y1, keep_prob)



# 출력층(6층)
W9 = tf.get_variable(name='W9', shape=[1024, 10], \
                     initializer=tf.contrib.layers.variance_scaling_initializer())
b9 = tf.Variable(tf.ones([10]))
z = tf.matmul(y1, W9) + b9
z_hat = tf.nn.softmax(z)
z = tf.argmax(z_hat, axis = 1)



correction_prediction = tf.equal(z, z_label)
accuracy = tf.reduce_mean(tf.cast(correction_prediction, "float"))
loss = - tf.reduce_sum(z_onehot*tf.log(z_hat), axis = 1)
optimizer = tf.train.AdamOptimizer(learning_rate=0.001)
train = optimizer.minimize(loss)

init = tf.global_variables_initializer()



# 세션 활성화
sess = tf.Session()
sess.run(init)

print("start")
for i in range(1, 11):
    for j in range(1, 500):
        batch_range_st = (j-1)*100
        batch_range_fi = j*100
        train_xs, train_ys = loader2.next_batch(trainX, trainY, batch_range_st, batch_range_fi)
        sess.run(train, feed_dict = {x_load : train_xs, z_onehot: train_ys, keep_prob : 0.9})
    train_acc = sess.run(accuracy, \
                         feed_dict = {x_load : train_xs, z_onehot : train_ys, keep_prob : 1.0})
    print('train %d 에폭 정확도'%i, train_acc)
    test_xs, test_ys =loader2.next_batch(testX, testY, 0, 100)
    test_acc = sess.run(accuracy, \
                        feed_dict = {x_load : test_xs, z_onehot : test_ys, keep_prob : 1.0})
    print('test  %d 에폭 정확도'%i, test_acc)
    print('+=====================+')

sess.close()

LOADING DATA
start
train 1 에폭 정확도 0.56
test  1 에폭 정확도 0.57
+=====================+
train 2 에폭 정확도 0.71
test  2 에폭 정확도 0.72
+=====================+


In [42]:
#문제 67. 개 고양이 사진이 있는 폴더를 만들고 그 폴더에 개사진 100장과 고양이 사진 100장을 넣고 아래와 같이 불러오는 함수를 생성하시오 !

import os
import numpy as np
import cv2

test_image = "c:\\b\\train_4000"

def image_load(path):
    file_list = os.listdir(path)
    for i in range(len(file_list)):
        file_list[i] = int(file_list[i][0:-4])
    file_list.sort()
    for i in range(len(file_list)):
        file_list[i] = path + "\\" + str(file_list[i]) + ".jpg"
    image =[]
    for i in file_list:
        img = cv2.imread(i)
        image.append(img)
    image = np.array(image)
    return image
    return file_list

print(image_load(test_image))

[[[[240 250 244]
   [245 255 249]
   [249 255 253]
   ...
   [166 192 204]
   [166 192 204]
   [165 191 203]]

  [[239 249 243]
   [244 254 248]
   [249 255 251]
   ...
   [164 190 202]
   [164 190 202]
   [163 189 201]]

  [[244 252 245]
   [245 253 246]
   [248 255 248]
   ...
   [162 188 200]
   [162 188 200]
   [161 187 199]]

  ...

  [[184 200 199]
   [183 199 198]
   [178 196 197]
   ...
   [142 136 117]
   [137 130 110]
   [143 136 116]]

  [[181 197 196]
   [179 195 194]
   [176 194 195]
   ...
   [141 135 116]
   [136 129 109]
   [145 138 118]]

  [[185 201 200]
   [180 196 195]
   [178 195 198]
   ...
   [135 129 110]
   [126 119  99]
   [135 128 108]]]


 [[[253 255 255]
   [253 255 255]
   [253 255 255]
   ...
   [250 255 254]
   [250 255 254]
   [250 255 254]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [252 254 254]
   [252 254 254]
   [252 254 254]]

  [[255 254 254]
   [255 254 254]
   [255 254 254]
   ...
   [255 255 255]
   [255 255 255]
   [255 255

In [22]:
#문제 68. 

import numpy as np
import csv

test_label = "c:\\b\\cat_dog_label.csv"

def label_load(path):
    file = open(path)
    labeldata = csv.reader(file)
    labellist = []
    for i in labeldata:
        labellist.append(i)
    labellist = np.array(labellist).astype(int)
    labellist = np.eye(2)[labellist]
    return np.squeeze(labellist, axis = 1)

print(label_load(test_label))

[[0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 

In [1]:
# * 개고양이 분류 데이터 전처리 함수 4가지
# 1. image_load
# 2. label_load
# 3. next_batch
# 4. shuffle_batch

#문제 69 위의 4개의 함수를 loader3.py로 생성해서 아래와 같이 실행되게 해보시오 !

import loader3


train_image = "c:\\b\\train_4000"
train_label = "c:\\b\\train_label_4000.csv"

print("LOADING DATA")
trainX = loader3.image_load(train_image)
print(trainX.shape)
trainY = loader3.label_load(train_label)
print(trainY.shape)

LOADING DATA
(4000, 128, 128, 3)
(4000, 2)
